### PR TITLE
Needed changes to let it run locally without sync to live server

### PR DESCRIPTION
**Pull request by MicrocontrollerExpert**

### CODE REVIEW

**Comment by Bilaboz** [comment]
Thanks for the PR, I'll check it when I get back home

**Comment by Bilaboz** [comment]
After checking, I don't really get why you want to modify the reward code. Same for setting the connection as verified. Can you explain a bit more please?

**Comment by MicrocontrollerExpert** [comment]
With the current reward code the rewards are wrong. I tested it with 5, 10, 15, 20, 25, and 30 cores and as I already posted in Discord the rewards with multiple nodes on the same rig are wrong. And with this change they are right again.

I couldn't find any code where the variable "verified" is changed from "no" to "yes". And so the number of permitted connections is permanently halved.

**Comment by Bilaboz** [comment]
I will have to reject your PR because of these reasons:
- you added multiple comments in the code
- conn.verified was used before, but we forgot to remove it
- checking if there is no pool password and name is error prone

side notes: if (poolName != "" && poolPassword != "") can be replaced with if (poolName && poolPassword)

**Comment by Bilaboz** [comment]
I removed conn.verified in this commit https://github.com/Bilaboz/duino-coin-pools/commit/cdf0ed868b7fbacd57a01ba8154240aa83eca0fe

**Pull request closed without merging**
